apiVersion: apps/v1
kind: Deployment
metadata:
  name: grupo23
  namespace: thymeleaf
spec:
  selector:
    matchLabels:
      app: grupo23
  replicas: 1
  template:
    metadata:
      labels:
         app: grupo23
    spec:
      imagePullSecrets:
         - name: github-secret
      containers:
         - name: grupo23
           image: localhost:5000/grupo_2_3:latest
           ports:
              - containerPort: 8080
           env:
              - name: db_host
                value: "190.146.2.119"
              - name: db_port
                value: "3306"
              - name: db_name
                value: "grupo_2_3"
              - name: db_username
                value: "grupo_2_3"
              - name: db_password
                value: "grupo_2_3"

---
apiVersion: v1
kind: Service
metadata:
  name: grupo23
  namespace: thymeleaf
spec:
#  type: NodePort
  selector:
    app: grupo23
  ports:
    - protocol: TCP
      port: 8080
#      nodePort: 30001
      targetPort: 8080     